name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Type check
      working-directory: ./backend
      run: npm run type-check
      
    - name: Build
      working-directory: ./backend
      run: npm run build
      
    - name: Run tests
      working-directory: ./backend
      run: npm run test:ci
      
    - name: Check for console.log statements
      run: |
        echo "Checking for console.log statements in production code..."
        if grep -r "console\.log" backend/src --exclude-dir=node_modules; then
          echo "⚠️ Found console.log statements. Consider removing them for production."
        else
          echo "✅ No console.log statements found."
        fi
